name: CI
# set a name for workflow for track with GitHub Actions
on:
  # determine the case, which start workflow 
  # push: triggered, when i push changes in "main"
  # pull_request: triggered, when i create or update "pull request" in branch main
  push:

    branches: [main]

  pull_request:

    branches: [main]


jobs:
  # section, where all tasks are set, which workflow must execute
  build-and-test:
    # - name: (concret–µ task (job) for build and testing my project)
    runs-on: ubuntu-latest
    # indicate, that will execute on virtual machine with lastes version of ubuntu
    steps:
      # determines the sequence of actions "steps" to be performed within this task
      - name: Checkout code
      # used GitHub actions for cloning my repository
        uses: actions/checkout@v3


      - name: Install dependencies
      # updated package manager and install base tools for compilation and build project via "make"
        run: |

          sudo apt-get update

          # flag "-y" = automatic "yes" in ever question

          sudo apt-get install -y build-essential

      
      - name: Build project with Make
        # start assembly with target "all" in Makefile
        run: |

          make all

      - name: Run tests
        # also tests
        run: |

          make test


















